import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
const ROOT=process.cwd(),V19=path.join(ROOT,'v19'),errors=[],warnings=[];const fail=m=>errors.push(m),warn=m=>warnings.push(m);
function walk(dir,ext=null){const out=[];for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())out.push(...walk(p,ext));else if(!ext||p.endsWith(ext))out.push(p)}return out}
if(!fs.existsSync(V19))fail('v19 root missing');
for(const f of ['v19/assets/v19.css','v19/assets/v19.js','v19/data/v14-map.js'])if(!fs.existsSync(path.join(ROOT,f)))fail(`missing ${f}`);
const html=walk(V19,'.html');if(html.length<9)fail(`expected at least 9 V19 HTML surfaces, got ${html.length}`);
const required=['index.html','manifesto/index.html','citizen/index.html','economy/index.html','state/index.html','projects/index.html','technology/index.html','evidence/index.html','map/index.html'];for(const r of required)if(!fs.existsSync(path.join(V19,r)))fail(`missing surface ${r}`);
const isRemote=s=>/^(https?:|mailto:|tel:|data:|javascript:|#|\/\/)/i.test(s);const attr=/(?:href|src)=["']([^"']+)["']/g;
for(const f of html){const rel=path.relative(ROOT,f).replaceAll('\\','/'),text=fs.readFileSync(f,'utf8');if(!text.includes('v19.css'))fail(`${rel}: shared CSS missing`);if(!text.includes('v19.js'))fail(`${rel}: shared runtime missing`);if(!text.includes('SINERGY'))warn(`${rel}: SINERGY identity not visible in source`);let m;while((m=attr.exec(text))){const raw=m[1];if(!raw||raw.includes('${')||isRemote(raw))continue;const clean=raw.split(/[?#]/)[0];if(!clean)continue;const t=path.resolve(path.dirname(f),clean);let ok=fs.existsSync(t);if(ok&&fs.statSync(t).isDirectory())ok=fs.existsSync(path.join(t,'index.html'));if(!ok)fail(`${rel}: broken local ref ${raw}`)} }
const ctx={window:{}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(V19,'data/v14-map.js'),'utf8'),ctx);const map=ctx.window.SINERGY_V14_MAP||[];if(map.length<40)fail(`V14 source map suspiciously small: ${map.length}`);const ids=new Set(),states=new Set(['preserved','normalized','superseded','research','prototype']);for(const x of map){if(!x.id||!x.name||!x.group||!x.state||!x.to||!x.note)fail(`bad V14 map row: ${JSON.stringify(x)}`);if(ids.has(x.id))fail(`duplicate V14 id ${x.id}`);ids.add(x.id);if(!states.has(x.state))fail(`${x.id}: invalid state ${x.state}`);const t=path.resolve(path.join(V19,'map'),x.to.split(/[?#]/)[0]);let ok=fs.existsSync(t);if(ok&&fs.statSync(t).isDirectory())ok=fs.existsSync(path.join(t,'index.html'));if(!ok)fail(`${x.id}: broken migration target ${x.to}`)}
const secret=/(api[_-]?key|private[_-]?key|secret|seed|mnemonic)\s*[:=]\s*["'][A-Za-z0-9_\/+=.-]{16,}["']/ig;for(const f of walk(V19)){if(!/\.(html|js|css|json|md)$/i.test(f))continue;const s=fs.readFileSync(f,'utf8');if(secret.test(s))fail(`${path.relative(ROOT,f)}: secret-like assignment`);secret.lastIndex=0}
const css=fs.readFileSync(path.join(V19,'assets/v19.css'),'utf8');for(const token of ['--green:','.radar{','.conflict{','.quote-stage{','prefers-reduced-motion'])if(!css.includes(token))fail(`visual system missing ${token}`);
console.log(`V19 HTML surfaces: ${html.length}`);console.log(`V14 known semantic branches mapped: ${map.length}`);for(const w of warnings)console.warn('WARN:',w);if(errors.length){for(const e of errors)console.error('ERROR:',e);console.error(`V19 STRUCTURAL FAILED: ${errors.length}`);process.exit(1)}console.log('V19 STRUCTURAL VALIDATION: PASS');
